# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
sudo: false
warnings_are_errors: true

addons:
  apt:
    packages:
      - libgdal-dev

os:
  - linux
  - osx

r:
  - 3.2
  - oldrel
  - release
  - devel

matrix:
  exclude:
  - os: osx
    r: 3.2
  - os: osx
    r: devel

notifications:
  email:
    on_success: change
    on_failure: change
