# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
warnings_are_errors: true

os:
  - linux
  - osx

r_packages:
  - covr

r:
  - 3.2
  - oldrel
  - release
  - devel

matrix:
  exclude:
  - os: osx
    r: 3.2
  - os: osx
    r: devel

# Only report coverage for the release version on linux
after_success:
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$TRAVIS_R_VERSION_STRING" == "release" ]; then Rscript -e 'library(covr); coveralls()'; fi

notifications:
  email:
    on_success: change
    on_failure: change