# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
warnings_are_errors: true

os:
  - linux
  - osx

r:
  - 3.2
  - oldrel
  - release
  - devel

matrix:
  exclude:
  - os: osx
    r: 3.2
  - os: osx
    r: devel

notifications:
  email:
    on_success: change
    on_failure: change